name: Fetch Google Reviews

on:
  schedule:
    - cron: '0 17 * * 0'  # Every Sunday at 11 AM CST
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch reviews from Outscraper
        env:
          API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
          BUSINESS_NAME: "Cemetery Brokerage, Memphis, TN"
        run: |
          RESPONSE=$(curl -s -X POST "https://api.app.outscraper.com/api/v1/maps/reviews" \
            -H "X-API-KEY: $API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"query\": \"$BUSINESS_NAME\", \"limit\": 100, \"language\": \"en\", \"sort\": \"newest\"}")
          
          echo "$RESPONSE" | jq '.' > reviews.json

      - name: Commit and push reviews.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reviews.json
          git diff --cached --quiet || git commit -m "Update reviews.json from Outscraper"
          git push
