name: Fetch Google Reviews

on:
  schedule:
    - cron: '0 17 * * 0'  # Every Sunday at 11 AM CST
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch reviews from Outscraper
        env:
          API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
          BUSINESS_NAME: "Cemetery Brokerage, Memphis, TN"
        run: |
          RESPONSE=$(curl -s -X POST "https://api.outscraper.com/maps/reviews-v3" \
            -H "X-API-KEY: $API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"queries\": [\"$BUSINESS_NAME\"], \"limit\": 100, \"language\": \"en\", \"reviewsSort\": \"newest\"}")

          echo "$RESPONSE" | jq '.' > reviews.json

      - name: Print reviews.json (for debugging, optional)
        run: cat reviews.json

      - name: Commit and push reviews.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reviews.json
          git commit -m "Update reviews.json from Outscraper" || echo "No changes to commit"
          git push
