name: Fetch Google Reviews

on:
  schedule:
    - cron: '0 17 * * 0'  # Every Sunday at 11 AM CST
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch reviews from Outscraper
        env:
          API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
        run: |
          curl -s -X GET "https://api.outscraper.cloud/maps/reviews-v3?query=Cemetery%20Brokerage%2C%20Memphis%2C%20TN&limit=100&async=false&language=en&reviewsSort=newest" \
            -H "X-API-KEY: $API_KEY" \
            -o reviews.json

      - name: Commit and push reviews.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reviews.json
          git diff --cached --quiet || git commit -m "Update reviews.json from Outscraper"
          git push
