name: Update Google Reviews Cache

on:
  schedule:
    # Runs every day at 1 AM UTC (adjust as you like)
    - cron: "0 1 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install node-fetch@3

    - name: Fetch and update reviews
      env:
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        PLACE_ID: ${{ secrets.PLACE_ID }}
      run: |
        node update-reviews.js

    - name: Commit & push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add reviews.json
          git commit -m "Update cached reviews [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
