name: Update Google Reviews Cache

on:
  schedule:
    - cron: '0 17 * * *' # Runs daily at 11 AM CST (5 PM UTC)
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch reviews from SerpApi
      run: |
        curl "https://serpapi.com/search.json?engine=google_maps_reviews&place_id=${{ secrets.PLACE_ID }}&api_key=${{ secrets.SERPAPI_KEY }}" \
          -o reviews-raw.json

        # Extract only reviews array using jq
        jq '.reviews' reviews-raw.json > reviews.json

    - name: Commit and push reviews
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add reviews.json
        git commit -m "Update reviews.json from SerpApi" || echo "No changes to commit"
        git push
