name: Fetch Google Reviews with Outscraper

on:
  schedule:
    - cron: '0 16 * * 0'  # Every Sunday at 11 AM CST
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Reviews from Outscraper
        run: |
          API_KEY="${{ secrets.OUTSCRAPER_API_KEY }}"
          BUSINESS_NAME="Cemetery Brokerage, Memphis, TN"
          ENCODED_NAME=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$BUSINESS_NAME'''))")

          curl -s -G "https://api.app.outscraper.com/maps/reviews" \
            -H "X-API-KEY: $API_KEY" \
            --data-urlencode "query=$BUSINESS_NAME" \
            --data-urlencode "limit=100" \
            --data-urlencode "language=en" \
            --data-urlencode "reviewsSort=newest" \
            -o reviews.json

      - name: Commit and Push reviews.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reviews.json
          git commit -m "Update reviews.json at $(date -u)" || echo "No changes to commit"
          git push
