name: Fetch Google Reviews with Outscraper

on:
  schedule:
    - cron: '0 16 * * 0'  # Every Sunday at 11 AM CST
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Reviews from Outscraper
        run: |
          API_KEY="${{ secrets.OUTSCRAPER_API_KEY }}"
          BUSINESS_NAME="Cemetery Brokerage, Memphis, TN"

          # Call Outscraper API
          RESPONSE=$(curl -s -X POST "https://api.app.outscraper.com/maps/reviews" \
            -H "X-API-KEY: $API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "'"$BUSINESS_NAME"'",
              "limit": 100,
              "language": "en",
              "reviewsSort": "newest"
            }')

          # Extract and save reviews
          echo "$RESPONSE" | jq '.' > reviews.json

      - name: Commit and Push reviews.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reviews.json
          git commit -m "Update reviews.json at $(date -u)"
          git push
