name: Fetch Google Reviews

on:
  schedule:
    - cron: '0 17 * * 0'  # 11 AM CST every Sunday (17:00 UTC)
  workflow_dispatch:

jobs:
  fetch-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch reviews from Outscraper
        env:
          API_KEY: ${{ secrets.OUTSCRAPER_API_KEY }}
          BUSINESS_NAME: "Cemetery Brokerage, Memphis, TN"
        run: |
          echo "Sending request to Outscraper with:"
          echo "Business: $BUSINESS_NAME"

          RESPONSE=$(curl -s -X POST "https://api.app.outscraper.com/maps/reviews" \
            -H "X-API-KEY: $API_KEY" \
            --data-urlencode "query=$BUSINESS_NAME" \
            --data-urlencode "limit=100" \
            --data-urlencode "language=en" \
            --data-urlencode "reviewsSort=newest")

          echo "$RESPONSE" | jq '.' > reviews.json

      - name: Commit and push reviews.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reviews.json
          git commit -m "Update reviews.json from Outscraper"
          git push
